"""Pydantic schemas for infographic image generation."""
from datetime import datetime
from typing import Literal, Optional, Union
from uuid import UUID

import re

from pydantic import AliasChoices, BaseModel, Field, field_validator, model_validator


class DiagramNode(BaseModel):
    """A single node or stage in an informational diagram."""

    step: int = Field(..., ge=1)
    title: str = Field(..., min_length=1)
    description: str = ""

    @field_validator("title")
    @classmethod
    def _strip_title(cls, value: str) -> str:
        if value is None:
            return ""
        value = value.strip()
        if value == "":
            raise ValueError("must not be empty")
        return value

    @field_validator("description")
    @classmethod
    def _strip_description(cls, value: str) -> str:
        if value is None:
            return ""
        return value.strip()


class VisualSpec(BaseModel):
    """Structured visual specification generated by the LLM."""

    day_number: int = Field(..., ge=1, validation_alias=AliasChoices("day_number", "day"))
    title: str = Field(..., min_length=1)
    subtitle: str = ""
    category: str = Field(default="", validation_alias=AliasChoices("category", "diagram_category"), exclude=True)
    theme: Literal["light_editorial", "light_minimal", "dark_tech", "blue_editorial", "dark-tech", "light-minimal", "blue-gradient"] = Field(default="light_editorial", exclude=True)
    visual_concept: str = Field(..., min_length=1, validation_alias=AliasChoices("visual_concept", "illustration_prompt"))
    style: Literal["dark-tech", "light-minimal", "blue-gradient"] = "light-minimal"
    aspect_ratio: Literal["1:1", "4:5", "16:9"] = "16:9"
    diagram_type: Literal[
        "process",
        "flowchart",
        "comparison",
        "lifecycle",
        "architecture",
        "steps",
        "concept",
        "hierarchy",
        "timeline",
        "list",
        "four_step",
        "before_after",
        "problem_solution",
        "document_pipeline",
        "cycle",
        "pyramid",
        "flow",
    ] = Field(default="process", validation_alias=AliasChoices("diagram_type", "layout_type"))
    diagram_nodes: list[Union[DiagramNode, str]] = Field(..., min_length=1, max_length=10, validation_alias=AliasChoices("diagram_nodes", "nodes", "steps"))
    key_points: list[str] = Field(..., min_length=3, max_length=5, validation_alias=AliasChoices("key_points", "checklist"))
    story: dict = Field(default_factory=dict, exclude=True)
    visual_elements: list[dict] = Field(default_factory=list, exclude=True)
    connections: list[dict] = Field(default_factory=list, exclude=True)
    icons: list[str] = Field(default_factory=list, exclude=True)

    @property
    def day(self) -> int:
        return self.day_number

    @day.setter
    def day(self, value: int) -> None:
        self.day_number = value

    @property
    def layout_type(self) -> str:
        return self.diagram_type

    @layout_type.setter
    def layout_type(self, value: str) -> None:
        self.diagram_type = value

    @property
    def nodes(self) -> list[DiagramNode]:
        return [node if isinstance(node, DiagramNode) else DiagramNode(step=idx + 1, title=str(node), description="") for idx, node in enumerate(self.diagram_nodes)]

    @nodes.setter
    def nodes(self, value) -> None:
        self.diagram_nodes = value

    @property
    def steps(self):
        return self.diagram_nodes

    @steps.setter
    def steps(self, value) -> None:
        self.diagram_nodes = value

    @property
    def checklist(self) -> list[str]:
        return self.key_points

    @checklist.setter
    def checklist(self, value: list[str]) -> None:
        self.key_points = value

    @property
    def illustration_prompt(self) -> str:
        return self.visual_concept

    @illustration_prompt.setter
    def illustration_prompt(self, value: str) -> None:
        self.visual_concept = value

    @field_validator("theme", mode="before")
    @classmethod
    def normalize_theme(cls, value):
        if value is None:
            return "light_editorial"
        if isinstance(value, str):
            mapping = {
                "dark-tech": "dark_tech",
                "light-minimal": "light_minimal",
                "blue-gradient": "blue_editorial",
            }
            return mapping.get(value, value)
        return value

    @model_validator(mode="before")
    @classmethod
    def normalize_legacy_and_semantic_fields(cls, data):
        if not isinstance(data, dict):
            return data

        normalized = dict(data)
        if "day_number" not in normalized and "day" in normalized:
            normalized["day_number"] = normalized["day"]
        if "diagram_type" not in normalized and "layout_type" in normalized:
            normalized["diagram_type"] = normalized["layout_type"]
        if "diagram_nodes" not in normalized and "nodes" in normalized:
            normalized["diagram_nodes"] = normalized["nodes"]
        if "diagram_nodes" not in normalized and "steps" in normalized:
            normalized["diagram_nodes"] = normalized["steps"]
        if "key_points" not in normalized and "checklist" in normalized:
            normalized["key_points"] = normalized["checklist"]
        if "visual_concept" not in normalized and "illustration_prompt" in normalized:
            normalized["visual_concept"] = normalized["illustration_prompt"]
        if "theme" not in normalized and "style" in normalized:
            normalized["theme"] = normalized["style"]
        return normalized

    @field_validator("diagram_nodes", mode="before")
    @classmethod
    def normalize_diagram_nodes(cls, nodes):
        if not nodes:
            raise ValueError("diagram_nodes must not be empty")
        normalized = []
        for idx, node in enumerate(nodes, start=1):
            if isinstance(node, DiagramNode):
                normalized.append(node)
            elif isinstance(node, str):
                cleaned = node.strip()
                if not cleaned:
                    raise ValueError("diagram node title must not be empty")
                normalized.append(DiagramNode(step=idx, title=cleaned, description=""))
            elif isinstance(node, dict):
                if "title" not in node and "step" not in node:
                    raise ValueError("diagram nodes must include a title or step")
                title_value = node.get("title")
                if title_value is None:
                    title_value = str(node)
                title_value = str(title_value).strip()
                if not title_value:
                    raise ValueError("diagram node title must not be empty")
                normalized.append(DiagramNode.model_validate({
                    "step": node.get("step", idx),
                    "title": title_value,
                    "description": str(node.get("description", "")).strip(),
                }))
            else:
                raise TypeError(f"Unsupported diagram node type: {type(node)!r}")
        return normalized

    @field_validator("key_points")
    @classmethod
    def normalize_key_points(cls, points):
        cleaned = []
        for point in points:
            if point is None:
                continue
            value = re.sub(r"\s+", " ", str(point).strip())
            if value:
                cleaned.append(value)
        if len(cleaned) < 3:
            raise ValueError("key_points must contain at least 3 non-empty values")
        return cleaned[:5]

    @field_validator("title", "subtitle", "visual_concept")
    @classmethod
    def strip_text(cls, value: str, info):
        if value is None:
            return value
        value = re.sub(r"\s+", " ", value.strip())
        if info.field_name in {"title", "visual_concept"} and not value:
            raise ValueError(f"{info.field_name} must not be empty")
        return value

    @model_validator(mode="after")
    def validate_title_and_context(self):
        if not self.title or not self.title.strip():
            raise ValueError("title must not be empty")
        if not self.visual_concept or not self.visual_concept.strip():
            raise ValueError("visual_concept must not be empty")
        if len(self.diagram_nodes) == 0:
            raise ValueError("diagram_nodes must not be empty")
        return self


class ImageRead(BaseModel):
    """ORM-mode schema for reading an ImageModel."""

    id: UUID
    post_id: UUID
    provider: str
    prompt: str
    visual_spec: dict
    file_path: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ImageResponse(BaseModel):
    """API response for image generation endpoint."""

    success: bool
    id: UUID
    post_id: UUID
    provider: str
    prompt: str
    visual_spec: dict
    file_path: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    status: str
    created_at: datetime
