"""Pydantic schemas for infographic image generation."""
from datetime import datetime
from typing import Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class VisualSpec(BaseModel):
    """Structured visual specification generated by Qwen3."""
    day_number: int = Field(..., ge=1)
    title: str = Field(..., min_length=1)
    subtitle: str
    visual_concept: str = Field(..., min_length=1)
    diagram_type: Literal["flowchart", "hierarchy", "comparison", "timeline", "list"]
    diagram_nodes: list[str] = Field(..., min_length=1, max_length=10)
    key_points: list[str] = Field(..., min_length=3, max_length=5)
    style: Literal["dark-tech", "light-minimal", "blue-gradient"]
    aspect_ratio: Literal["1:1", "4:5", "16:9"]


class ImageRead(BaseModel):
    """ORM-mode schema for reading an ImageModel."""
    id: UUID
    post_id: UUID
    provider: str
    prompt: str
    visual_spec: dict
    file_path: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ImageResponse(BaseModel):
    """API response for image generation endpoint."""
    success: bool
    id: UUID
    post_id: UUID
    provider: str
    prompt: str
    visual_spec: dict
    file_path: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    status: str
    created_at: datetime
